version: "3.2"

networks:
  api:

services:
  irita-api:
    image: irita-api
    container_name: irita-api
    hostname: irita-api
    restart: unless-stopped
    environment:
      IRITA_SERVER_PORT: 80
      IRITA_LOGGER_LEVEL: debug
      IRITA_IRITA_UERNAME: test_key_name
      IRITA_IRITA_PASSWORD: test_password
      IRITA_IRITA_MNEMONIC: supreme zero ladder chaos blur lake dinner warm rely voyage scan dilemma future spin victory glance legend faculty join man mansion water mansion exotic
      IRITA_IRITA_COIN: 100000uirita
      IRITA_IRITA_GASLIMIT: 200000
      IRITA_IRITA_TLSENABLE: "false"
      IRITA_IRITA_RPCADDRESS: http://47.100.192.234:26657
      IRITA_IRITA_WSADDRESS: ws://47.100.192.234:26657
      IRITA_IRITA_GRPCADDRESS: 47.100.192.234:9090
      IRITA_IRITA_CHAINID: testing
      IRITA_IRITA_PROJECTID: TestProjectID
      IRITA_IRITA_PROJECTKEY: TestProjectKey
      IRITA_IRITA_CHAINACCOUNTADDRESS: TestChainAccountAddress
    ports:
      - "80:80"
    volumes:
      - ./irita-sdk-go:/root/irita-sdk-go
      - ./logs:/irita-api/logs
    networks:
      - api