server:
  port: 8080

logger:
  level: debug

irita:
  username: test_key_name
  password: test_password
  mnemonic: supreme zero ladder chaos blur lake dinner warm rely voyage scan dilemma future spin victory glance legend faculty join man mansion water mansion exotic
  coin: 100000uirita
  gasLimit: 200000
  tlsEnable: false
  rpcAddress: http://47.100.192.234:26657
  wsAddress: ws://47.100.192.234:26657
  grpcAddress: 47.100.192.234:9090
  chainId: testing
  projectId: TestProjectID
  projectKey: TestProjectKey
  chainAccountAddress: TestChainAccountAddress